### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by yhlleo** [wjko2/Linguistically-Informed-Specificity-and-Semantic-Plausibility-for-Dialogue-Generation#1]
`
Code for Wei-Jen Ko, Greg Durrett and Junyi Jessy Li, "Training command: and Semantic Plausibility for Dialogue Generation", The AAAI Conference on Artificial Intelligence (NAACL), 2019`

Both the paper title and conference name are not correct here in the readme document.

**Comment by wjko2** [comment]
Fixed, Thanks!
